#!/usr/bin/env bash
# Fake fuer uname: gibt bei -s vor, ein anderes System zu sein. FAKE_UNAME=Darwin|Linux
case "${1:-}" in
  -s) echo "${FAKE_UNAME:-Darwin}" ;;
  *)  /usr/bin/uname "$@" 2>/dev/null || uname.exe "$@" ;;
esac
